In [3]:
import pandas as pd
def load_data():
    path=r'dataset\train.csv'
    global data
    data=pd.read_csv(path)
    return data
load_data()

,tBodyAcc-mean()-X,tBodyAcc-mean()-Y,tBodyAcc-mean()-Z,tBodyAcc-std()-X,tBodyAcc-std()-Y,tBodyAcc-std()-Z,tBodyAcc-mad()-X,tBodyAcc-mad()-Y,tBodyAcc-mad()-Z,tBodyAcc-max()-X,...,fBodyBodyGyroJerkMag-kurtosis(),"angle(tBodyAccMean,gravity)","angle(tBodyAccJerkMean),gravityMean)","angle(tBodyGyroMean,gravityMean)","angle(tBodyGyroJerkMean,gravityMean)","angle(X,gravityMean)","angle(Y,gravityMean)","angle(Z,gravityMean)",subject,Activity
0,0.288585,-0.020294,-0.132905,-0.995279,-0.983111,-0.913526,-0.995112,-0.983185,-0.923527,-0.934724,...,-0.710304,-0.112754,0.030400,-0.464761,-0.018446,-0.841247,0.179941,-0.058627,1,STANDING
1,0.278419,-0.016411,-0.123520,-0.998245,-0.975300,-0.960322,-0.998807,-0.974914,-0.957686,-0.943068,...,-0.861499,0.053477,-0.007435,-0.732626,0.703511,-0.844788,0.180289,-0.054317,1,STANDING
2,0.279653,-0.019467,-0.113462,-0.995380,-0.967187,-0.978944,-0.996520,-0.963668,-0.977469,-0.938692,...,-0.760104,-0.118559,0.177899,0.100699,0.808529,-0.848933,0.180637,-0.049118,1,STANDING
3,0.279174,-0.026201,-0.123283,-0.996091,-0.983403,-0.990675,-0.997099,-0.982750,-0.989302,-0.938692,...,-0.482845,-0.036788,-0.012892,0.640011,-0.485366,-0.848649,0.181935,-0.047663,1,STANDING
4,0.276629,-0.016570,-0.115362,-0.998139,-0.980817,-0.990482,-0.998321,-0.979672,-0.990441,-0.942469,...,-0.699205,0.123320,0.122542,0.693578,-0.615971,-0.847865,0.185151,-0.043892,1,STANDING
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7347,0.299665,-0.057193,-0.181233,-0.195387,0.039905,0.077078,-0.282301,0.043616,0.060410,0.210795,...,-0.880324,-0.190437,0.829718,0.206972,-0.425619,-0.791883,0.238604,0.049819,30,WALKING_UPSTAIRS
7348,0.273853,-0.007749,-0.147468,-0.235309,0.004816,0.059280,-0.322552,-0.029456,0.080585,0.117440,...,-0.680744,0.064907,0.875679,-0.879033,0.400219,-0.771840,0.252676,0.050053,30,WALKING_UPSTAIRS
7349,0.273387,-0.017011,-0.045022,-0.218218,-0.103822,0.274533,-0.304515,-0.098913,0.332584,0.043999,...,-0.304029,0.052806,-0.266724,0.864404,0.701169,-0.779133,0.249145,0.040811,30,WALKING_UPSTAIRS
7350,0.289654,-0.018843,-0.158281,-0.219139,-0.111412,0.268893,-0.310487,-0.068200,0.319473,0.101702,...,-0.344314,-0.101360,0.700740,0.936674,-0.589479,-0.785181,0.246432,0.025339,30,WALKING_UPSTAIRS
7351,0.351503,-0.012423,-0.203867,-0.269270,-0.087212,0.177404,-0.377404,-0.038678,0.229430,0.269013,...,-0.740738,-0.280088,-0.007739,-0.056088,-0.616956,-0.783267,0.246809,0.036695,30,WALKING_UPSTAIRS

In [4]:
def test_data():
    test_path=r'dataset\test.csv'
    global data
    test_data=pd.read_csv(test_path)
    return test_data
test_data()

,tBodyAcc-mean()-X,tBodyAcc-mean()-Y,tBodyAcc-mean()-Z,tBodyAcc-std()-X,tBodyAcc-std()-Y,tBodyAcc-std()-Z,tBodyAcc-mad()-X,tBodyAcc-mad()-Y,tBodyAcc-mad()-Z,tBodyAcc-max()-X,...,fBodyBodyGyroJerkMag-kurtosis(),"angle(tBodyAccMean,gravity)","angle(tBodyAccJerkMean),gravityMean)","angle(tBodyGyroMean,gravityMean)","angle(tBodyGyroJerkMean,gravityMean)","angle(X,gravityMean)","angle(Y,gravityMean)","angle(Z,gravityMean)",subject,Activity
0,0.257178,-0.023285,-0.014654,-0.938404,-0.920091,-0.667683,-0.952501,-0.925249,-0.674302,-0.894088,...,-0.705974,0.006462,0.162920,-0.825886,0.271151,-0.720009,0.276801,-0.057978,2,STANDING
1,0.286027,-0.013163,-0.119083,-0.975415,-0.967458,-0.944958,-0.986799,-0.968401,-0.945823,-0.894088,...,-0.594944,-0.083495,0.017500,-0.434375,0.920593,-0.698091,0.281343,-0.083898,2,STANDING
2,0.275485,-0.026050,-0.118152,-0.993819,-0.969926,-0.962748,-0.994403,-0.970735,-0.963483,-0.939260,...,-0.640736,-0.034956,0.202302,0.064103,0.145068,-0.702771,0.280083,-0.079346,2,STANDING
3,0.270298,-0.032614,-0.117520,-0.994743,-0.973268,-0.967091,-0.995274,-0.974471,-0.968897,-0.938610,...,-0.736124,-0.017067,0.154438,0.340134,0.296407,-0.698954,0.284114,-0.077108,2,STANDING
4,0.274833,-0.027848,-0.129527,-0.993852,-0.967445,-0.978295,-0.994111,-0.965953,-0.977346,-0.938610,...,-0.846595,-0.002223,-0.040046,0.736715,-0.118545,-0.692245,0.290722,-0.073857,2,STANDING
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2942,0.310155,-0.053391,-0.099109,-0.287866,-0.140589,-0.215088,-0.356083,-0.148775,-0.232057,0.185361,...,-0.750809,-0.337422,0.346295,0.884904,-0.698885,-0.651732,0.274627,0.184784,24,WALKING_UPSTAIRS
2943,0.363385,-0.039214,-0.105915,-0.305388,0.028148,-0.196373,-0.373540,-0.030036,-0.270237,0.185361,...,-0.700274,-0.736701,-0.372889,-0.657421,0.322549,-0.655181,0.273578,0.182412,24,WALKING_UPSTAIRS
2944,0.349966,0.030077,-0.115788,-0.329638,-0.042143,-0.250181,-0.388017,-0.133257,-0.347029,0.007471,...,-0.467179,-0.181560,0.088574,0.696663,0.363139,-0.655357,0.274479,0.181184,24,WALKING_UPSTAIRS
2945,0.237594,0.018467,-0.096499,-0.323114,-0.229775,-0.207574,-0.392380,-0.279610,-0.289477,0.007471,...,-0.617737,0.444558,-0.819188,0.929294,-0.008398,-0.659719,0.264782,0.187563,24,WALKING_UPSTAIRS
2946,0.153627,-0.018437,-0.137018,-0.330046,-0.195253,-0.164339,-0.430974,-0.218295,-0.229933,-0.111527,...,-0.436940,0.598808,-0.287951,0.876030,-0.024965,-0.660080,0.263936,0.188103,24,WALKING_UPSTAIRS

In [7]:
def data_info():
    shape=data.shape
    print(shape)
    info=data.info
    print(info)
    df=data.head(5)
    #print(df)

data_info()

(7352, 563)
<bound method DataFrame.info of       tBodyAcc-mean()-X  tBodyAcc-mean()-Y  tBodyAcc-mean()-Z  \
0              0.288585          -0.020294          -0.132905
1              0.278419          -0.016411          -0.123520
2              0.279653          -0.019467          -0.113462
3              0.279174          -0.026201          -0.123283
4              0.276629          -0.016570          -0.115362
...                 ...                ...                ...
7347           0.299665          -0.057193          -0.181233
7348           0.273853          -0.007749          -0.147468
7349           0.273387          -0.017011          -0.045022
7350           0.289654          -0.018843          -0.158281
7351           0.351503          -0.012423          -0.203867

      tBodyAcc-std()-X  tBodyAcc-std()-Y  tBodyAcc-std()-Z  tBodyAcc-mad()-X  \
0            -0.995279         -0.983111         -0.913526         -0.995112
1            -0.998245         -0.975300         -0.960322         -0.998807
2            -0.995380         -0.967187         -0.978944         -0.996520
3            -0.996091         -0.983403         -0.990675         -0.997099
4            -0.998139         -0.980817         -0.990482         -0.998321
...                ...               ...               ...               ...
7347         -0.195387          0.039905          0.077078         -0.282301
7348         -0.235309          0.004816          0.059280         -0.322552
7349         -0.218218         -0.103822          0.274533         -0.304515
7350         -0.219139         -0.111412          0.268893         -0.310487
7351         -0.269270         -0.087212          0.177404         -0.377404

      tBodyAcc-mad()-Y  tBodyAcc-mad()-Z  tBodyAcc-max()-X  ...  \
0            -0.983185         -0.923527         -0.934724  ...
1            -0.974914         -0.957686         -0.943068  ...
2            -0.963668         -0.977469         -0.938692  ...
3            -0.982750         -0.989302         -0.938692  ...
4            -0.979672         -0.990441         -0.942469  ...
...                ...               ...               ...  ...
7347          0.043616          0.060410          0.210795  ...
7348         -0.029456          0.080585          0.117440  ...
7349         -0.098913          0.332584          0.043999  ...
7350         -0.068200          0.319473          0.101702  ...
7351         -0.038678          0.229430          0.269013  ...

      fBodyBodyGyroJerkMag-kurtosis()  angle(tBodyAccMean,gravity)  \
0                           -0.710304                    -0.112754
1                           -0.861499                     0.053477
2                           -0.760104                    -0.118559
3                           -0.482845                    -0.036788
4                           -0.699205                     0.123320
...                               ...                          ...
7347                        -0.880324                    -0.190437
7348                        -0.680744                     0.064907
7349                        -0.304029                     0.052806
7350                        -0.344314                    -0.101360
7351                        -0.740738                    -0.280088

      angle(tBodyAccJerkMean),gravityMean)  angle(tBodyGyroMean,gravityMean)  \
0                                 0.030400                         -0.464761
1                                -0.007435                         -0.732626
2                                 0.177899                          0.100699
3                                -0.012892                          0.640011
4                                 0.122542                          0.693578
...                                    ...                               ...
7347                              0.829718                          0.206972
7348                              0.875679                         -0.879033
7349                             -0.266724                          0.864404
7350                              0.700740                          0.936674
7351                             -0.007739                         -0.056088

      angle(tBodyGyroJerkMean,gravityMean)  angle(X,gravityMean)  \
0                                -0.018446             -0.841247
1                                 0.703511             -0.844788
2                                 0.808529             -0.848933
3                                -0.485366             -0.848649
4                                -0.615971             -0.847865
...                                    ...                   ...
7347                             -0.425619             -0.791883
7348                              0.400219             -0.771840
7349                              0.701169             -0.779133
7350                             -0.589479             -0.785181
7351                             -0.616956             -0.783267

      angle(Y,gravityMean)  angle(Z,gravityMean)  subject          Activity
0                 0.179941             -0.058627        1          STANDING
1                 0.180289             -0.054317        1          STANDING
2                 0.180637             -0.049118        1          STANDING
3                 0.181935             -0.047663        1          STANDING
4                 0.185151             -0.043892        1          STANDING
...                    ...                   ...      ...               ...
7347              0.238604              0.049819       30  WALKING_UPSTAIRS
7348              0.252676              0.050053       30  WALKING_UPSTAIRS
7349              0.249145              0.040811       30  WALKING_UPSTAIRS
7350              0.246432              0.025339       30  WALKING_UPSTAIRS
7351              0.246809              0.036695       30  WALKING_UPSTAIRS

[7352 rows x 563 columns]>

In [8]:
def feture():
    global X
    X = load_data().drop(columns=["subject", "Activity"])
    return X
feture()

,tBodyAcc-mean()-X,tBodyAcc-mean()-Y,tBodyAcc-mean()-Z,tBodyAcc-std()-X,tBodyAcc-std()-Y,tBodyAcc-std()-Z,tBodyAcc-mad()-X,tBodyAcc-mad()-Y,tBodyAcc-mad()-Z,tBodyAcc-max()-X,...,fBodyBodyGyroJerkMag-meanFreq(),fBodyBodyGyroJerkMag-skewness(),fBodyBodyGyroJerkMag-kurtosis(),"angle(tBodyAccMean,gravity)","angle(tBodyAccJerkMean),gravityMean)","angle(tBodyGyroMean,gravityMean)","angle(tBodyGyroJerkMean,gravityMean)","angle(X,gravityMean)","angle(Y,gravityMean)","angle(Z,gravityMean)"
0,0.288585,-0.020294,-0.132905,-0.995279,-0.983111,-0.913526,-0.995112,-0.983185,-0.923527,-0.934724,...,-0.074323,-0.298676,-0.710304,-0.112754,0.030400,-0.464761,-0.018446,-0.841247,0.179941,-0.058627
1,0.278419,-0.016411,-0.123520,-0.998245,-0.975300,-0.960322,-0.998807,-0.974914,-0.957686,-0.943068,...,0.158075,-0.595051,-0.861499,0.053477,-0.007435,-0.732626,0.703511,-0.844788,0.180289,-0.054317
2,0.279653,-0.019467,-0.113462,-0.995380,-0.967187,-0.978944,-0.996520,-0.963668,-0.977469,-0.938692,...,0.414503,-0.390748,-0.760104,-0.118559,0.177899,0.100699,0.808529,-0.848933,0.180637,-0.049118
3,0.279174,-0.026201,-0.123283,-0.996091,-0.983403,-0.990675,-0.997099,-0.982750,-0.989302,-0.938692,...,0.404573,-0.117290,-0.482845,-0.036788,-0.012892,0.640011,-0.485366,-0.848649,0.181935,-0.047663
4,0.276629,-0.016570,-0.115362,-0.998139,-0.980817,-0.990482,-0.998321,-0.979672,-0.990441,-0.942469,...,0.087753,-0.351471,-0.699205,0.123320,0.122542,0.693578,-0.615971,-0.847865,0.185151,-0.043892
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7347,0.299665,-0.057193,-0.181233,-0.195387,0.039905,0.077078,-0.282301,0.043616,0.060410,0.210795,...,-0.070157,-0.588433,-0.880324,-0.190437,0.829718,0.206972,-0.425619,-0.791883,0.238604,0.049819
7348,0.273853,-0.007749,-0.147468,-0.235309,0.004816,0.059280,-0.322552,-0.029456,0.080585,0.117440,...,0.165259,-0.390738,-0.680744,0.064907,0.875679,-0.879033,0.400219,-0.771840,0.252676,0.050053
7349,0.273387,-0.017011,-0.045022,-0.218218,-0.103822,0.274533,-0.304515,-0.098913,0.332584,0.043999,...,0.195034,0.025145,-0.304029,0.052806,-0.266724,0.864404,0.701169,-0.779133,0.249145,0.040811
7350,0.289654,-0.018843,-0.158281,-0.219139,-0.111412,0.268893,-0.310487,-0.068200,0.319473,0.101702,...,0.013865,0.063907,-0.344314,-0.101360,0.700740,0.936674,-0.589479,-0.785181,0.246432,0.025339
7351,0.351503,-0.012423,-0.203867,-0.269270,-0.087212,0.177404,-0.377404,-0.038678,0.229430,0.269013,...,-0.058402,-0.387052,-0.740738,-0.280088,-0.007739,-0.056088,-0.616956,-0.783267,0.246809,0.036695

In [10]:
def target():
    global y
    y = load_data()["Activity"]
    return y
target()

0               STANDING
1               STANDING
2               STANDING
3               STANDING
4               STANDING
              ...
7347    WALKING_UPSTAIRS
7348    WALKING_UPSTAIRS
7349    WALKING_UPSTAIRS
7350    WALKING_UPSTAIRS
7351    WALKING_UPSTAIRS
Name: Activity, Length: 7352, dtype: str

In [9]:
def test_feture():
    global test_X
    test_X = test_data().drop(columns=["subject", "Activity"])
    return test_X

In [11]:
def test_target():
    global test_y
    test_y = test_data()["Activity"]

    return test_y
test_target()

0               STANDING
1               STANDING
2               STANDING
3               STANDING
4               STANDING
              ...
2942    WALKING_UPSTAIRS
2943    WALKING_UPSTAIRS
2944    WALKING_UPSTAIRS
2945    WALKING_UPSTAIRS
2946    WALKING_UPSTAIRS
Name: Activity, Length: 2947, dtype: str

In [12]:
from src.data_loader import feture, target
import pandas as pd
from sklearn.feature_selection import SelectKBest, mutual_info_classif
from sklearn.feature_selection import SelectKBest, f_classif
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.feature_selection import SelectFromModel

In [13]:
def all_features_fs():
    selector = SelectKBest(
        score_func=f_classif,
        k="all"
    )
    return selector


def f_classif_fs():
    
    selector = SelectKBest(f_classif, k=150)
    return selector


def mutual_info_classif_fs():
    
    selector = SelectKBest(mutual_info_classif, k=150)
    return selector


def ExtraTreesClassifier_fc():
    
    selector = SelectFromModel(
        ExtraTreesClassifier(n_estimators=300, random_state=42, n_jobs=-1),
        max_features=150
    )
    return selector

In [14]:
from sklearn.pipeline import Pipeline
from sklearn.feature_selection import SelectKBest, f_classif, mutual_info_classif
from sklearn.preprocessing import PowerTransformer, StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from src.feature_selection import ExtraTreesClassifier
from sklearn.svm import SVC
from src.data_loader import feture, target
from src.data_loader import test_feture, test_target
import time

In [15]:
def extra_trees_model():
    start=time.time()
    extra_trees_model = Pipeline([
           ("transform", PowerTransformer(method="yeo-johnson")),
    ("selection", SelectKBest(f_classif, k=350)),
    ("classifier", ExtraTreesClassifier(
        n_estimators=500,
    max_depth=15,
    min_samples_split=5,
    min_samples_leaf=2,
    max_features="sqrt",
    class_weight="balanced",
    random_state=42,
    n_jobs=-1
    ))
])
    end= time.time()
    print('model training time is :', start - end)

    return extra_trees_model

In [16]:
def logistic_regression_model():
    start=time.time()
    logistic_regression_model= Pipeline([
        ("scaler", StandardScaler()),
        ("select", SelectKBest(f_classif, k=250)),
        ("model", LogisticRegression(
            C=1.0,
            max_iter=5000,
            solver="lbfgs",
          #  multi_class="auto",
            random_state=42
        ))
    ])
    end= time.time()
    print('model training time is :', start - end)

    return logistic_regression_model

In [17]:
def knn_model():
    start=time.time()
    knn_model = Pipeline([
        ("scaler", StandardScaler()),
        ("select", SelectKBest(f_classif, k=150)),
        ("model", KNeighborsClassifier(
            n_neighbors=7,
            weights="distance",
            metric="minkowski",
            p=2,
            n_jobs=-1
        ))
    ])
    end= time.time()
    print('model training time is :', start - end)
    return knn_model

In [18]:
def rbf_svm_model():
    start=time.time()
    svm = Pipeline([
        ("scaler", StandardScaler()),
        ("select", SelectKBest(f_classif, k=150)),
        ("model", SVC(
            kernel="rbf",
            C=10,
            gamma="scale",
            class_weight="balanced",
            random_state=42
        ))
    ])
    end= time.time()
    print('model training time is :', start - end)

    return svm

In [19]:
from sklearn.ensemble import ExtraTreesClassifier
def model_prediction():
    X_train=feture()
    y_train=target()
    model=logistic_regression_model()
    fitted_model=model.fit(X_train, y_train)
    val_pred = fitted_model.predict(X_train)
    
    return  model, val_pred, y_train

In [20]:
def model_pred_test():
    model, val_pred, y_train=model_prediction()
    tf=test_feture()
    tt=test_target()   
    test_output=model.predict(tf)   
    return test_output

In [21]:
from sklearn.metrics import accuracy_score, classification_report
from src.models import model_prediction, model_pred_test
from src.data_loader import test_feture, test_target
import json

In [22]:
def traing():
    model, val_pred, y_train=model_prediction()
    train_acc=accuracy_score(y_train, val_pred)
    
    train_report =classification_report(y_train, val_pred)
    
    

    return train_acc, train_report

In [23]:
def testing():
    test_prediction = model_pred_test()
    tg=test_target()
    test_acc=accuracy_score(tg,test_prediction)
    
    test_report =classification_report(tg,test_prediction)
    return test_acc, test_report

In [24]:


def create_result(file_name):
    train_acc, train_report=traing()
    test_acc, test_report=testing()
    
    results = {
    "train_accuracy": train_acc,
    "train_classification_report": train_report,
    "test_accuracy": test_acc,
    "test_classification_report": test_report
    }
    with open(file_name, "w") as f:
        json.dump(results, f, indent=4)

    print("results Saved to ", file_name)

In [26]:
from src.evaluation import traing, testing, create_result
def main():
    train_acc, train_report=traing()
    test_acc, test_report=testing()
    
    print(f"model performance in traning  is {train_acc} accuracy \n model performance in traing  is \n {train_report} \n model performance in testing  is \n {test_acc} \n model performance in testing is \n  {test_report}")
    #give file name
    create_result(r'results\f_classif\logistic_regression_model.json')
main()

model training time is : 0.0
model training time is : 0.0
model performance in traning  is 0.9782372143634385 accuracy
 model performance in traing  is
                     precision    recall  f1-score   support

            LAYING       1.00      1.00      1.00      1407
           SITTING       0.95      0.93      0.94      1286
          STANDING       0.93      0.95      0.94      1374
           WALKING       1.00      1.00      1.00      1226
WALKING_DOWNSTAIRS       1.00      1.00      1.00       986
  WALKING_UPSTAIRS       1.00      1.00      1.00      1073

          accuracy                           0.98      7352
         macro avg       0.98      0.98      0.98      7352
      weighted avg       0.98      0.98      0.98      7352

 model performance in testing  is
 0.9487614523243977
 model performance in testing is
                      precision    recall  f1-score   support

            LAYING       1.00      1.00      1.00       537
           SITTING       0.97      0.86      0.91       491
          STANDING       0.88      0.97      0.92       532
           WALKING       0.91      0.99      0.95       496
WALKING_DOWNSTAIRS       0.99      0.97      0.98       420
  WALKING_UPSTAIRS       0.97      0.90      0.93       471

          accuracy                           0.95      2947
         macro avg       0.95      0.95      0.95      2947
      weighted avg       0.95      0.95      0.95      2947

model training time is : 0.0
model training time is : 0.0
results Saved to  results\f_classif\logistic_regression_model.json